name: CocoaPods

on: [push]

jobs:
  lint:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.0"
      - uses: actions/checkout@v2
      - name: Lint Cocoapods
        run: pod lib lint --allow-warnings
