name: CommitChecks

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.2"
      - uses: actions/checkout@v2
      - name: Run Test
        run: xcodebuild -scheme Verge-Package -resultBundlePath results/VergeTests.xcresult test -destination 'platform=iOS Simulator,name=iPhone 8,OS=16.2' -derivedDataPath ./DerivedData | xcpretty

      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: |
            results/VergeTests.xcresult
        if: success() || failure()

  build-package-on-swiftpm:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.2"
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
