name: CommitChecks

on: [push]

jobs:
  test:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.4"
      - uses: actions/checkout@v2
      - name:
        run: xcodebuild -scheme Verge-Package -resultBundlePath results/VergeTests.xcresult test -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.4' -derivedDataPath ./DerivedData | xcbeautify

     - uses: kishikawakatsumi/xcresulttool@v1
       with:
         path: |
           results/VergeTests.xcresult        
       if: success() || failure()

  lint:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.4"
      - uses: actions/checkout@v2
      - name: Lint Cocoapods
        run: pod lib lint --allow-warnings

  build-package-on-swiftpm:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.4"
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v

  build-package-on-xcodebuild:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.4"
      - uses: actions/checkout@v2
      - name: Build
        run: xcodebuild -scheme Verge-Package -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.4' | xcbeautify