name: CommitChecks

on: [push]

jobs:
  test:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.4"
      - uses: actions/checkout@v2
      - name: Run test
        run: fastlane test_light
  lint:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.4"
      - uses: actions/checkout@v2
      - name: Lint Cocoapods
        run: pod lib lint --allow-warnings
  build-with-swiftpm:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.4"
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
