name: Cocoapods

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Force xcode 12
        run: sudo xcode-select -switch /Applications/Xcode_12.0.app
      - uses: actions/checkout@v2
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Lint Cocoapods
        run: pod lib lint
