name: Cocoapods

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: '12.1'
      - uses: actions/checkout@v2
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Lint Cocoapods
        run: pod lib lint --allow-warnings
