name: Release

on:
  push:
    tags:
      - "*"

jobs:
  pod-trunk-push:
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.0"
      - uses: actions/checkout@v2
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push Verge.podspec --allow-warnings
