name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  pod-trunk-push:
    runs-on: macOS-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.4"
      - name: Deploy
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push Verge.podspec --allow-warnings
