name: Swift

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: '12.1'
      - uses: actions/checkout@v1
      - name: Build
        run: swift build -v
