name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Force xcode 12.0
      run: sudo xcode-select -switch /Applications/Xcode_12.0.app
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
